# Generated by Django 2.2 on 2020-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefingTime', models.TimeField(null=True)),
                ('reminders', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
