# Generated by Django 2.2 on 2020-07-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200709_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='_client_history_+', related_query_name='appointment', to='clients.Client'),
        ),
    ]
