# Generated by Django 2.2 on 2020-07-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20200709_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='history',
        ),
    ]
