# Generated by Django 2.2 on 2020-07-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200709_2221'),
        ('clients', '0008_remove_client_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='appointments', related_query_name='appointment', to='appointments.Appointment'),
        ),
    ]
