# Generated by Django 2.2 on 2020-07-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
