# Generated by Django 2.2 on 2020-07-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20200710_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phoneNumber',
            field=models.IntegerField(default=7774448888),
            preserve_default=False,
        ),
    ]
