# Generated by Django 2.2 on 2020-07-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20200710_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='history',
        ),
    ]
