# Generated by Django 2.2 on 2020-07-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_remove_client_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
    ]
