# Generated by Django 2.2 on 2020-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20200718_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientNotes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
