# Generated by Django 2.2 on 2020-07-25 21:16

import clients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_auto_20200720_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(clients.models.get_sentinel_user), related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
