# Generated by Django 2.2 on 2020-07-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20200725_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contactNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
