# Generated by Django 2.2 on 2020-07-20 18:53

from django.conf import settings
from django.db import migrations, models
import flights.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=6)),
                ('tailNumber', models.CharField(max_length=6)),
                ('parking', models.CharField(max_length=8)),
                ('routing', models.TextField()),
                ('flightDate', models.DateField()),
                ('scheduledTOA', models.TimeField()),
                ('scheduledTOD', models.TimeField()),
                ('estimatedTOA', models.TimeField()),
                ('estimatedTOD', models.TimeField()),
                ('actualTOA', models.TimeField(null=True)),
                ('actualTOD', models.TimeField(null=True)),
                ('serviceDuration', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=models.SET(flights.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduledTOA'],
            },
        ),
    ]
