# Generated by Django 2.2 on 2020-07-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffMembers', '0002_staffmember_supervisor'),
        ('clients', '0016_auto_20200718_2351'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['flightDate']},
        ),
        migrations.AddField(
            model_name='flight',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flightCoordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flightCoordinator', to='staffMembers.StaffMember'),
        ),
        migrations.AddField(
            model_name='flight',
            name='lavService',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavService', to='staffMembers.StaffMember'),
        ),
        migrations.AddField(
            model_name='flight',
            name='trafficCoordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trafficCoordinator', to='staffMembers.StaffMember'),
        ),
    ]
