# Generated by Django 2.2 on 2020-07-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20200720_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='actualTOA',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='actualTOD',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimatedTOA',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimatedTOD',
            field=models.TimeField(blank=True),
        ),
    ]
