# Generated by Django 2.2 on 2020-07-25 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200722_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(flights.models.get_sentinel_user), related_name='flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
