# Generated by Django 2.2 on 2020-07-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20200725_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['scheduledTOA']},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flightDate',
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimatedTOA',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimatedTOD',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
