# Generated by Django 2.2 on 2020-07-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20200730_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='scheduledTOA',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduledTOD',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
