# Generated by Django 2.2 on 2020-07-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20200730_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flightNumber',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='flight',
            name='parking',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='flight',
            name='tailNumber',
            field=models.CharField(max_length=60),
        ),
    ]
