# Generated by Django 2.2 on 2020-07-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20200730_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='actualTOA',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='actualTOD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimatedTOA',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimatedTOD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduledTOA',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduledTOD',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
