# Generated by Django 2.2 on 2020-07-20 18:53

from django.conf import settings
from django.db import migrations, models
import staffMembers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('contactNumber', models.IntegerField(null=True)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('team', models.TextField(null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=models.SET(staffMembers.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
