# Generated by Django 2.2 on 2020-07-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffMembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffMember', to='staffMembers.StaffMember'),
        ),
    ]
