# Generated by Django 2.2 on 2020-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20200711_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
