# Generated by Django 2.2 on 2020-07-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20200711_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentTime',
        ),
    ]
