# Generated by Django 2.2 on 2020-07-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20200713_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
