# Generated by Django 2.2 on 2020-07-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_appointment_appointmenttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentNotes',
            field=models.TextField(blank=True),
        ),
    ]
