# Generated by Django 2.2 on 2020-07-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_appointment_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointmentDate', 'appointmentTime', '-id']},
        ),
    ]
