# Generated by Django 2.2 on 2020-07-13 23:31

import appointments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_auto_20200713_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_STARTED'), (2, 'IN_PROGRESS'), (3, 'COMPLETED')], default=appointments.utils.AppointmentStatusTypes(1)),
        ),
    ]
